baseURL = "https://noematic.eu/"
languageCode = "en-en"
theme = "noematic"

# navigation
[menu]

  #[[menu.header]]
  #name = "About"
  #URL = "#about"
  #weight = 2


  #[[menu.footer]]
  #name = "About"
  #URL = "#about"
  #weight = 2


[params]

  sections = ["showcase"]
  gcount = "noematic-eu"

  [params.logo]
    text1 = "Noematic"

  [params.footer]
      copyright = "2025 © Noematic. All rights reserved."
